Traceback (most recent call last):
  File "/home/rohan.kumar/tex-tar/main.py", line 104, in <module>
    Pipeline().run()
  File "/home/rohan.kumar/tex-tar/main.py", line 47, in __init__
    self._build_architecture()
  File "/home/rohan.kumar/tex-tar/main.py", line 75, in _build_architecture
    self.validator = Validator(self.cfg)
  File "/home/rohan.kumar/tex-tar/src/validation/val.py", line 35, in __init__
    self.val_loader = DataLoader(self.val_dataset,batch_size=640,shuffle=False, num_workers=cfg["num_workers"],pin_memory=True)
AttributeError: 'Validator' object has no attribute 'val_dataset'. Did you mean: 'train_dataset'?
Traceback (most recent call last):
  File "/home/rohan.kumar/tex-tar/main.py", line 104, in <module>
    Pipeline().run()
  File "/home/rohan.kumar/tex-tar/main.py", line 47, in __init__
    self._build_architecture()
  File "/home/rohan.kumar/tex-tar/main.py", line 75, in _build_architecture
    self.validator = Validator(self.cfg)
  File "/home/rohan.kumar/tex-tar/src/validation/val.py", line 35, in __init__
    self.val_loader = DataLoader(self.val_dataset,batch_size=640,shuffle=False, num_workers=cfg["num_workers"],pin_memory=True)
AttributeError: 'Validator' object has no attribute 'val_dataset'. Did you mean: 'train_dataset'?
